### Home
GET http://localhost:5001/
###Se pone esto de abajo para que el plugin de requests detecte que este es otra ruta
###Obtener productos
GET http://localhost:5001/productos
### Crear producto
POST http://localhost:5001/productos
Content-Type: application/json 

{
    "nombre": "Lápiz",
    "categoria": 2,
    "cantidad": 100,
    "precio": 2
}
### Modificar producto
PUT http://localhost:5001/productos/620c2a60ced1d25de4a2f7e7
Content-Type: application/json

{
    "nombre": "Producto 1 2.0",
    "cantidad": 4,
    "precio": 40,
    "categoria": 2
}
### Obtener un producto en específico
GET http://localhost:5001/productos/621968f3f1572c44aa657637
### Filtrar productos
GET http://localhost:5001/productos?filtro=Libro
### Eliminar producto
DELETE http://localhost:5001/productos/620c2a60ced1d25de4a2f7e7